Repository Cola-Dori/todo-list, pull requests merged in 2022-04, with the labels that each got.

#12 Feat: mock server와 mock db 세팅#11
  .eslintrc.json
  index.html
  package-lock.json
  package.json
  src/app.js
  src/db.json
  src/server.js
Labels: Feat, FE

#17 Feat: 마크업 일부 공유용 PR #16
  assets/icons/style.css
  assets/icons/todo.svg
  assets/icons/todo.ttf
  assets/icons/todo.woff
  index.html
  styles/bootstrap-grid.min.css
Labels: Chore, FE

#18 Feat: 마크업 및 스타일 추가 #16
  component.html
  index.html
  styles/bootstrap-grid.min.css
  styles/main.scss
  styles/scss/base/_reset.scss
  styles/scss/components/_header.scss
  styles/scss/components/_main.scss
  styles/scss/components/_todo-column.scss
  styles/scss/components/_todo-list.scss
  styles/scss/constants/_box-shadow.scss
  styles/scss/constants/_colors.scss
  styles/scss/mixins/_scrollbar.scss
  styles/scss/modules/_badge.scss
  styles/scss/modules/_buttons.scss
Labels: Design, FE

#19 Refactor: lowdb 저장위치 수정 #11
  .eslintrc.json
  package-lock.json
  package.json
  src/app.js
  src/db.json
  src/server.js
  src/store.js
  src/utils/utils.js
  webpack.config.js
Labels: Refactor, FE

#20 Chore: utils.js 추가
  src/utils/utils.js
Labels: Chore

#22 Feat: 컬럼에 카드 등록 진행 중 #21
  index.html
  src/app.js
  src/index.js
  src/utils/utils.js
  styles/scss/constants/_colors.scss
Labels: Feat, Refactor, Fix, FE

#23 Feat: 초기 렌더링 구현
  index.html
  package-lock.json
  package.json
  src/Views/TodoColumns.js
  src/Views/TodoItem.js
  src/Views/TodoList.js
  src/app.js
  src/index.js
  src/store.js
  src/utils/utils.js
  src/webdb.js
  webpack.config.js
Labels: Feat, Chore, Style, FE

#24 Refactor: View 이름 변경
  src/Views/TodoCard.js
  src/Views/TodoColumn.js
  src/Views/TodoColumns.js
  src/app.js
  src/webdb.js
Labels: Refactor, FE

#26 Refactor: 생성자호출시 매겨변수 전달
  src/Views/TodoCard.js
  src/Views/TodoColumn.js
  src/Views/TodoColumns.js
Labels: Refactor

#28 Refactor: 돔 렌더링 로직 변경
  src/Views/TodoCard.js
  src/Views/TodoColumn.js
  src/Views/TodoColumns.js
Labels: Refactor

#31 Feat: textarea auto resize, p <-> textarea 변환
  src/Views/TodoCard.js
  src/Views/TodoColumn.js
  src/Views/TodoColumns.js
  src/utils/utils.js
  styles/scss/components/_todo-column.scss
  styles/scss/components/_todo-list.scss
Labels: Feat, FE

#32 Feat: Modal
  index.html
  src/Views/TodoCard.js
  src/Views/TodoColumns.js
  src/app.js
  src/utils/utils.js
  styles/main.scss
  styles/scss/components/_modal.scss
Labels: Feat

#33 Feat: 카드 등록 추가
  src/Views/Modal.js
  src/Views/TodoCard.js
  src/Views/TodoColumn.js
  src/app.js
  src/store.js
  src/utils/utils.js
  styles/scss/components/_modal.scss
Labels: Feat, FE

#34 Style: 메서드 호출 순서, 메서드 선언 순서 변경
  src/Views/TodoCard.js
  src/Views/TodoColumn.js
  src/Views/TodoColumns.js
Labels: Style

#35 Feat: 카드 등록 #21
  src/Views/Modal.js
  src/Views/TodoCard.js
  src/Views/TodoColumn.js
  src/Views/TodoColumns.js
  src/store.js
  src/webdb.js
  styles/scss/components/_todo-list.scss
  styles/scss/modules/_buttons.scss
Labels: Feat, Fix, FE

#37 Chore: 배포용 패키지 및 스크립트 추가 #36
  index.html
  package-lock.json
  package.json
  styles/main.scss
  webpack.config.js
Labels: Chore

#38 Fix: TodoColumns, TodoColumn init 메서드 변경
  package-lock.json
  package.json
  src/Views/TodoColumn.js
  src/Views/TodoColumns.js
Labels: Chore, Fix, FE

#40 Design: 드래그 앤 드롭
  styles/scss/components/_header.scss
  styles/scss/components/_todo-column.scss
  styles/scss/components/_todo-list.scss
Labels: Design
